title: jobs

locations: Brussel / Antwerpen / Gent
types:
  - type: dev
    yourProfile: >
      We are looking for a passionate and talented developer with a drive to keep on learning and improving his/her skills.
    learn: >
      … or eager to build experience in these cutting edge technologies?
  - type: tester
    yourProfile: >
      We are looking for a passionate and talented tester with a drive to keep on learning and improving his/her skills.
    learn: >
      … or an eagerness to build and expand your knowledge of these testing knowledge objectives and techniques.
  - type: devops
    yourProfile: >
      We are looking for a passionate and talented developer/engineer with a drive to keep on learning and improving his/her skills.
  - type: support
    yourProfile: >
      We are looking for a passionate and talented support engineer with a drive to keep on learning and improving his/her skills.
  - type: fa
    yourProfile: >
      We are looking for a passionate functional analyst with a drive to learn the business and improve his/her skills.



doYou:
  - have the drive to keep on learning?
  - like to be a part of a young, dynamic group of people who share the same values?
  - feel responsible for what you deliver?
  - choose quality over quantity?
  - have the dedication to bring quality and professionalism to our customers?
  - want to be assisted by the best technical people (20+ yrs exp.) to boost your development and career?
  - want to learn the latest technologies to keep your passion sparked?
  - speak Dutch with a profound knowledge of English?

areYou:
  - not afraid to ask questions or can we convince you not to be?
  - capable of working independently?
  - communicative and a teamplayer?

ourOffer:
  - Competitive salary
  - Company car with fuel card
  - Mobile phone
  - 32 holidays (12 ADV)
  - Hospital & Group insurance
  - Meal vouchers

ourEdge:
  - Personal coaching by our competence center
  - Career plans and accompanying training
  - Fun teambuilding activities

dutchOnly: Native Dutch speaking.

xp:
  - type: medior
    desc: 5-8 years experience.
    extra: (or verifiable passion – for example with an active Github account)
  - type: senior
    desc: 5+ years experience (+8 preferred).


jobs:
  - id: account-manager
    title: "Account Manager"
    xp: other
    xpDesc: "&nbsp;"
    active: true
    skills:
      - Perfect Nederlandstalig
      - Je bent een initiatiefnemer & self-motivator
      - Je gaat geen uitdaging uit de weg, kan de ‘extra mile’ gaan en hebt een winnaarsmentaliteit
      - Je krijgt energie van nieuwe contacten en commerciële successen
      - Je hebt interesse in mensen en technologie
      - Je weet wanneer je de juiste persoon voor je hebt om een vacature in te vullen
      - Je bent een interessante gesprekspartner voor iedereen die met je praat
      - Je bent een goede luisteraar en communicator
      - Je vindt snel oplossingen en bent er steeds naar op zoek
      - Je bent gedisciplineerd
      - Je krijgt ‘the job done’ wat ze ook aan jou vragen en weet wat prioritair is
      - Je gaat vooruit en het is soms moeilijk om je bij te houden
      - Je staat steeds open om bij te leren en bent een ‘quick learner’
      - Je brengt negotiaties tot een goed einde en kan het hoofd koel te houden
      - Je bent sociaal, extravert en kan een ruimte vullen met jouw aanwezigheid
    trackRecord:
      - Je behaalde een hoger diploma in Sales of Bedrijfskunde of gelijkwaardig door ervaring.
      - Ervaring met lead generatie, hunting, farming, enz.
      - Je hebt een ervaring opgebouwd in B2B business development of services (consultative selling)
      - Je hebt een aantoonbaar track record van succesvolle deals en je kent de markt, de trends en de concurrenten
      - Je bent een geweldige netwerker en bereid om communities van stakeholders te ontwikkelen en te onderhouden
    plus:
      - Een bestaand netwerk is een sterke plus
      - Affiniteit met talent sourcing & IT is een plus
      - Frans is een plus
    ourOffer:
      - Een leuke groep collega’s gedreven door passie en resultaten
      - Competitief loon (vast + variabel)
      - Bedrijfswagen met tankkaart
      - High-end laptop
      - GSM-toestel
      - 26 verlofdagen (6 ADV)
      - Hospitalisatie- en groepsverzekering
      - Maaltijd- en ecocheques

  - id: medior-frontend
    title: Medior Frontend Developer
    xp: medior
    type: dev
    active: false
    techs:
      - title: Got experience with
        learn: true
        techs:
          - JavaScript and TypeScript
          - SASS, SCSS or Post-CSS
          - Angular, React or Vue.js
          - Bootstrap or Foundation
          - Jasmine, Mocha or Jest
          - NodeJS and Express
          - Bluebird or RxJS
          - socket.io, superagent and Redux
          - Babel, Webpack or Gulp
      - title: ... and perhaps also with
        techs:
          - UX Design Guidelines
          - SQL or No-SQL database(s)
          - Design Patterns and Dependency Injection
          - Scrum and Kanban
          - DevOps and Continuous Integration

  - id: medior-dotnet
    title: Medior Full Stack .NET Developer
    xp: medior
    type: dev
    active: false
    techs:
      - title: Got frontend experience with
        techs:
          - JavaScript or TypeScript
          - SASS, SCSS or Post-CSS
          - Angular, React or Vue.js
      - title: Got backend experience with
        learn: true
        techs:
          - .NET Core
          - EntityFramework
          - ASP.NET WebApi and REST
          - LINQ, Generics and async/await
          - Unit Testing
      - title: And also with
        techs:
          - SQL or No-SQL database(s)
          - Design Patterns and Dependency Injection
          - Scrum and Kanban
          - DevOps and Continuous Integration

  - id: medior-fullstack
    title: Medior Full Stack Developer
    xp: medior
    type: dev
    active: false
    techs:
      - title: Got frontend experience with
        techs:
          - JavaScript or TypeScript
          - SASS, SCSS or Post-CSS
          - Angular, React or Vue.js
      - title: Got backend experience with either
        learn: true
        techs:
          - "NodeJS: Express, npm, Webpack, ..."
          - "PHP: Laravel, Composer, Doctrine, ..."
          - "Python: Django, pip, ..."
      - title: And also with
        techs:
          - SQL or No-SQL database(s)
          - Design Patterns and Dependency Injection
          - Scrum and Kanban
          - DevOps and Continuous Integration
          - Unit Testing

  - id: medior-java
    title: Medior Full Stack Java Developer
    xp: medior
    type: dev
    active: false
    techs:
      - title: Got frontend experience with
        techs:
          - JavaScript or TypeScript
          - SASS, SCSS or Post-CSS
          - Angular, React or Vue.js
      - title: Got backend experience with
        learn: true
        techs:
          - Java 11 and Android
          - Hibernate and Spring
          - Generics and Lambdas
          - Unit Testing
      - title: And also with
        techs:
          - SQL or No-SQL database(s)
          - Design Patterns and Dependency Injection
          - Scrum and Kanban
          - DevOps and Continuous Integration

  - id: test-engineer
    title: Automation Test Engineer
    xp: senior
    type: tester
    active: true
    techs:
      - title: Knowledge
        learn: true
        techs:
          - Traceability and Test Matrixes
          - V-Model
          - Equivalence partitioning & boundary value analysis
          - White box and black box testing
          - Selenium, Katalon or Ranorex
      - title: Career plan
        subtitle: To grow into a role as
        techs:
          - Test Automation Engineer
          - Security Tester
          - Test Manager
          - Tester-Analyst

  - id: functional-analyst
    title: Functional Analyst
    xp: senior
    type: fa
    active: true
    techs:
      - title: Knowledge
        techs:
          - UML
          - Domain Modelling
          - SQL
          - Scrum
      - title: Personality
        techs:
          - A Problem Solver
          - Solution Oriented
          - A Bridge Creator
          - Flexible and Stress Resistant

  - id: devops-engineer
    title: DevOps Engineer
    xpDesc: 2+ years experience.
    type: devops
    active: false
    techs:
      - title: Got development experience with
        techs:
          - JavaScript
          - .NET or Java
          - SQL Server or Oracle
          - PowerShell, Python or bash
          - Scrum
      - title: Got operations experience with
        techs:
          -  Docker or Kubernetes
          -  Azure or AWS
          -  Puppet, Chef or DSC
          -  Windows or Linux
          -  Continuous Integration

  - id: linux-engineer
    title: Linux Engineer
    xpDesc: 1+ year experience.
    type: linux
    active: false
    techs:
      - techs:
          - Debian or CentOS or ...
          - Apache / Nginx
          - Puppet / Chef / Ansible
          - Bash, Python, Perl or PowerShell Core
          - Databases (Mysql, Postgres, MariaDb, ...)
          - Network protocols (TCP, HTTP, SMTP, DNS, ...)

  - id: support-engineer
    title: Support Engineer
    xpDesc: 1+ year experience.
    xpExtra: Trilingual (NL, FR, EN).
    xpSupressLanguage: true
    type: support
    active: false
    techs:
      - title: Got experience with
        techs:
          - Microsoft Windows Server
          - Windows and Office or Linux
          - Exchange Server and Active Directory
          - Backup & Restore, Printers, Shares
          - DNS, Firewalls, Routers
      - title: And optionally also with
        techs:
          - Virtualisation
          - SQL Server or Oracle
          - Azure or AWS
          - PowerShell or bash

  - id: scrum-master
    title: Scrum Master
    xpDesc: 1+ year experience.
    xpExtra: 50% ScrumMaster, 50% Development.
    type: dev
    active: false
    techs:
      - title: Got experience with
        techs:
          - Scrum, XP and Kanban
          - SAFe or LeSS
          - Coaching & Facilitating
          - Squads & Tribes
      - title: And also with
        techs:
          - .NET or Java
          - WebApi or Spring
          - EntityFramework or Hibernate

  - id: senior-frontend
    title: Frontend Developer
    xp: senior
    type: dev
    active: false
    techs:
      - title: Got experience with
        learn: true
        techs:
          - JavaScript and TypeScript
          - SASS, SCSS or Post-CSS
          - Angular, React or Vue.js
          - Bootstrap or Foundation
          - Jasmine, Mocha or Jest
          - NodeJS and Express
          - Bluebird or RxJS
          - socket.io, superagent and Redux
          - Babel, Webpack or Gulp
      - title: ... and perhaps also with
        techs:
          - UX Design Guidelines
          - SQL or No-SQL database(s)
          - Design Patterns and Dependency Injection
          - Scrum and Kanban
          - DevOps and Continuous Integration

  - id: senior-dotnet
    title: Full Stack .NET Developer
    xp: senior
    type: dev
    active: true
    techs:
      - title: Got frontend experience with
        techs:
          - JavaScript or TypeScript
          - SASS, SCSS or Post-CSS
          - Angular, React or Vue.js
          - RxJS and Redux
      - title: Got backend experience with
        learn: true
        techs:
          - .NET Core
          - EntityFramework
          - ASP.NET WebApi and REST
          - LINQ, Generics and async/await
          - Unit Testing
          - AWS or Azure
      - title: And also with
        techs:
          - SQL or No-SQL database(s)
          - Design Patterns and Dependency Injection
          - Scrum and Kanban
          - DevOps and Continuous Integration

  - id: senior-fullstack
    title: Full Stack Developer
    xp: senior
    type: dev
    active: false
    techs:
      - title: Got frontend experience with
        techs:
          - JavaScript or TypeScript
          - SASS, SCSS or Post-CSS
          - Angular, React or Vue.js
          - RxJS and Redux
      - title: Got backend experience with either
        learn: true
        techs:
          - "NodeJS: Express, npm, Webpack, ..."
          - "PHP: Laravel, Composer, Doctrine, ..."
          - "Python: Django, pip, ..."
          - AWS or Azure
      - title: And also with
        techs:
          - SQL or No-SQL database(s)
          - Design Patterns and Dependency Injection
          - Scrum and Kanban
          - DevOps and Continuous Integration
          - Unit Testing

  - id: senior-java
    title: Full Stack Java Developer
    xp: senior
    type: dev
    active: true
    techs:
      - title: Got frontend experience with
        techs:
          - JavaScript or TypeScript
          - SASS, SCSS or Post-CSS
          - Angular, React or Vue.js
          - RxJS and Redux
      - title: Got backend experience with
        learn: true
        techs:
          - Java 11 and Android
          - Hibernate and Spring
          - Generics and Lambdas
          - Unit Testing
          - AWS or Azure
      - title: And also with
        techs:
          - SQL or No-SQL database(s)
          - Design Patterns and Dependency Injection
          - Scrum and Kanban
          - DevOps and Continuous Integration
